<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="TestPasswordValidator" duration-ms="24" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="24" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
      <class name="TestPasswordValidator">
        <test-method status="PASS" signature="exceptionWithBlankValue()[pri:0, instance:TestPasswordValidator@7d9d1a19]" name="exceptionWithBlankValue" duration-ms="2" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[blank value]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: blank value
at PasswordValidator.haveSmallCharactars(PasswordValidator.java:14)
at TestPasswordValidator.exceptionWithBlankValue(TestPasswordValidator.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceptionWithBlankValue -->
        <test-method status="PASS" signature="testCapitalCharsAreValidatedCorrectly()[pri:0, instance:TestPasswordValidator@7d9d1a19]" name="testCapitalCharsAreValidatedCorrectly" duration-ms="1" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCapitalCharsAreValidatedCorrectly -->
        <test-method status="PASS" signature="testSmallCharsAreValidatedCorrectly()[pri:0, instance:TestPasswordValidator@7d9d1a19]" name="testSmallCharsAreValidatedCorrectly" duration-ms="0" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSmallCharsAreValidatedCorrectly -->
        <test-method status="PASS" signature="testSmallCharsAreValidatedCorrectly_negativeCase()[pri:0, instance:TestPasswordValidator@7d9d1a19]" name="testSmallCharsAreValidatedCorrectly_negativeCase" duration-ms="1" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSmallCharsAreValidatedCorrectly_negativeCase -->
        <test-method status="PASS" signature="testSpecialCharsAreValidatedCorrectly()[pri:0, instance:TestPasswordValidator@7d9d1a19]" name="testSpecialCharsAreValidatedCorrectly" duration-ms="0" started-at="2021-09-23T18:26:43 IST" finished-at="2021-09-23T18:26:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSpecialCharsAreValidatedCorrectly -->
      </class> <!-- TestPasswordValidator -->
    </test> <!-- Command line test -->
  </suite> <!-- TestPasswordValidator -->
</testng-results>
